modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "numismatic_reimagined"
version = "${version}"
displayName = "Numismatic Reimagined"
authors = "Gaspard4i"
description = '''
A currency mod for Minecraft. Adds bronze, silver, gold, netherite and star coins.
'''

[[dependencies.numismatic_reimagined]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatic_reimagined]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatic_reimagined]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"
