org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Mod
mod_version=2.0.0-alpha.1
maven_group=dev.gaspard4i
archives_base_name=numismatic_reimagined
mod_id=numismatic_reimagined

# Minecraft
minecraft_version=1.21.1
java_version=21

# Architectury
architectury_api_version=13.0.8
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.8-SNAPSHOT

# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.115.1+1.21.1

# NeoForge
neoforge_version=21.1.95
moddevgradle_version=2.0.78

# Mappings
parchment_mc_version=1.21.1
parchment_version=2024.11.17

# Libraries
owo_lib_version=0.12.15+1.21

# Dev environment mods (runtime only)
jei_version=19.21.0.247
jade_version_fabric=15.10.5+fabric
jade_version_neoforge=15.10.5+neoforge

# Testing
junit_version=5.10.2
mockito_version=5.11.0
jacoco_version=0.8.12
